#!/usr/bin/env zsh 

# Zsh
export HISTFILE="$XDG_STATE_HOME/zsh/history"
export HISTSIZE=10000
export SAVEHIST=10000

# Editor
export EDITOR="nvim"
export VISUAL="nvim"

# Go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
